In [1]:
import numpy as np
import pickle

In [2]:
ohe_sex=pickle.load(open('ohe_sex.pkl','rb'))

In [3]:
ohe_embarked=pickle.load(open('ohe_embarked.pkl','rb'))
clf=pickle.load(open('clf_file.pkl','rb'))

In [4]:
#Assume user input
# pclass/gender/age/Sibsp/parch/Fare/Embarked
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [5]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [6]:
test_input_sex= ohe_sex.transform(test_input[:,1].reshape(1,1))

/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [7]:
test_input[:,1].reshape(1,1)

array([['male']], dtype=object)

In [8]:
test_input_sex

array([[0., 1.]])

In [9]:
test_input_embarked=ohe_embarked.transform([['S']])

In [10]:
test_input_embarked

array([[0., 0., 1.]])

In [11]:
test_input_age=test_input[:, 2].reshape(1,1)

In [12]:
test_input_transform=np.concatenate((test_input[:, [0,3,4,5]],test_input_sex,test_input_age,test_input_embarked), axis=1)


In [13]:
test_input_transform.shape

(1, 10)

In [14]:
pred=clf.predict(test_input_transform) 

In [16]:
pred

array([1], dtype=int64)

the pesron with age 31,gender as male, alone predict as survived 