In [24]:
import numpy as np
import pickle

In [25]:
ohe_sex=pickle.load(open('ohe_sex.pkl','rb'))

In [26]:
ohe_embarked=pickle.load(open('ohe_embarked.pkl','rb'))
clf=pickle.load(open('clf_file.pkl','rb'))

In [27]:
#Assume user input
# pclass/gender/age/Sibsp/parch/Fare/Embarked
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [28]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [46]:
test_input_sex= ohe_sex.transform(test_input[:,1].reshape(1,1))

/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [48]:
test_input[:,1].reshape(1,1)

array([['male']], dtype=object)

In [45]:
test_input_sex

array([[1.]])

In [33]:
test_input_embarked=ohe_embarked.transform([['S']])

In [34]:
test_input_embarked

array([[0., 0., 1.]])

In [15]:
test_input_age=test_input[:, 2].reshape(1,1)

In [16]:
test_input_transform=np.concatenate((test_input[:, [0,3,4,5]],test_input_sex,test_input_age,test_input_embarked), axis=1)


In [17]:
test_input_transform.shape

(1, 9)

In [31]:
pred=clf.predict(test_input_transform) 

ValueError: X has 9 features, but DecisionTreeClassifier is expecting 10 features as input.